// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Buddy_Beacon

#include "../ui.h"

void ui_del_waypoint_screen_init(void)
{
    ui_del_waypoint = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_del_waypoint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel16 = lv_obj_create(ui_del_waypoint);
    lv_obj_set_width(ui_Panel16, 98);
    lv_obj_set_height(ui_Panel16, 28);
    lv_obj_set_x(ui_Panel16, 0);
    lv_obj_set_y(ui_Panel16, 1);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, 0);
    lv_obj_set_y(ui_Label47, -1);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "Delete Waypoint");
    lv_obj_set_style_text_font(ui_Label47, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_del_waypoint);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, 0);
    lv_obj_set_y(ui_Label48, -21);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "^");

    ui_Label49 = lv_label_create(ui_del_waypoint);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -57);
    lv_obj_set_y(ui_Label49, 0);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "<");

}
