// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Buddy_Beacon

#include "../ui.h"

void ui_enter_message_blank_screen_init(void)
{
    ui_enter_message_blank = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_enter_message_blank, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label67 = lv_label_create(ui_enter_message_blank);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label67, 0);
    lv_obj_set_y(ui_Label67, -20);
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "Enter Message:");
    lv_obj_set_style_text_font(ui_Label67, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label68 = lv_label_create(ui_enter_message_blank);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label68, -2);
    lv_obj_set_y(ui_Label68, -2);
    lv_obj_set_align(ui_Label68, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label68, "");
    lv_obj_set_style_text_font(ui_Label68, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}
