// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Buddy_Beacon

#include "../ui.h"

void ui_sub_beacon4_screen_init(void)
{
    ui_sub_beacon4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_sub_beacon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_sub_beacon4);
    lv_obj_set_width(ui_Panel6, 90);
    lv_obj_set_height(ui_Panel6, 28);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 1);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label83 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label83, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label83, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label83, 0);
    lv_obj_set_y(ui_Label83, -1);
    lv_obj_set_align(ui_Label83, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label83, "");
    lv_obj_set_style_text_font(ui_Label83, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label84 = lv_label_create(ui_sub_beacon4);
    lv_obj_set_width(ui_Label84, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label84, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label84, 0);
    lv_obj_set_y(ui_Label84, -21);
    lv_obj_set_align(ui_Label84, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label84, "^");

}
