// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Buddy_Beacon

#include "../ui.h"

void ui_sub_message4_screen_init(void)
{
    ui_sub_message4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_sub_message4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_sub_message4);
    lv_obj_set_width(ui_Panel7, 90);
    lv_obj_set_height(ui_Panel7, 28);
    lv_obj_set_x(ui_Panel7, 0);
    lv_obj_set_y(ui_Panel7, 1);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, 0);
    lv_obj_set_y(ui_Label65, -1);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label65, "");
    lv_obj_set_style_text_font(ui_Label65, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label66 = lv_label_create(ui_sub_message4);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label66, 0);
    lv_obj_set_y(ui_Label66, -21);
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label66, "^");

}
