// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Buddy_Beacon

#include "../ui.h"

void ui_tracking_n_screen_init(void)
{
    ui_tracking_n = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_tracking_n, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label57 = lv_label_create(ui_tracking_n);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label57, 0);
    lv_obj_set_y(ui_Label57, -20);
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "Tracking");
    lv_obj_set_style_text_font(ui_Label57, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_tracking_n);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, 0);
    lv_obj_set_y(ui_Label58, 4);
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "^");
    lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

}
