// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Buddy_Beacon

#include "../ui.h"

void ui_tracking_w_screen_init(void)
{
    ui_tracking_w = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_tracking_w, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label61 = lv_label_create(ui_tracking_w);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, 0);
    lv_obj_set_y(ui_Label61, -20);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "Tracking");
    lv_obj_set_style_text_font(ui_Label61, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label62 = lv_label_create(ui_tracking_w);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label62, 0);
    lv_obj_set_y(ui_Label62, 4);
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "<");
    lv_obj_set_style_text_font(ui_Label62, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

}
