// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Buddy_Beacon

#include "../ui.h"

void ui_tracking_e_screen_init(void)
{
    ui_tracking_e = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_tracking_e, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label59 = lv_label_create(ui_tracking_e);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, 0);
    lv_obj_set_y(ui_Label59, -20);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "Tracking");
    lv_obj_set_style_text_font(ui_Label59, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60 = lv_label_create(ui_tracking_e);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, 0);
    lv_obj_set_y(ui_Label60, 4);
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, ">");
    lv_obj_set_style_text_font(ui_Label60, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

}
