// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Buddy_Beacon

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_main_beacons
void ui_main_beacons_screen_init(void);
lv_obj_t * ui_main_beacons;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_sub_beacon1
void ui_sub_beacon1_screen_init(void);
lv_obj_t * ui_sub_beacon1;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

// SCREEN: ui_sub_beacon2
void ui_sub_beacon2_screen_init(void);
lv_obj_t * ui_sub_beacon2;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label37;
// CUSTOM VARIABLES

// SCREEN: ui_sub_beacon3
void ui_sub_beacon3_screen_init(void);
lv_obj_t * ui_sub_beacon3;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label40;
// CUSTOM VARIABLES

// SCREEN: ui_sub_beacon4
void ui_sub_beacon4_screen_init(void);
lv_obj_t * ui_sub_beacon4;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label83;
lv_obj_t * ui_Label84;
// CUSTOM VARIABLES

// SCREEN: ui_track_beacon
void ui_track_beacon_screen_init(void);
lv_obj_t * ui_track_beacon;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
// CUSTOM VARIABLES

// SCREEN: ui_tracking_n
void ui_tracking_n_screen_init(void);
lv_obj_t * ui_tracking_n;
lv_obj_t * ui_Label57;
lv_obj_t * ui_Label58;
// CUSTOM VARIABLES

// SCREEN: ui_tracking_e
void ui_tracking_e_screen_init(void);
lv_obj_t * ui_tracking_e;
lv_obj_t * ui_Label59;
lv_obj_t * ui_Label60;
// CUSTOM VARIABLES

// SCREEN: ui_tracking_s
void ui_tracking_s_screen_init(void);
lv_obj_t * ui_tracking_s;
lv_obj_t * ui_Label63;
lv_obj_t * ui_Label64;
// CUSTOM VARIABLES

// SCREEN: ui_tracking_w
void ui_tracking_w_screen_init(void);
lv_obj_t * ui_tracking_w;
lv_obj_t * ui_Label61;
lv_obj_t * ui_Label62;
// CUSTOM VARIABLES

// SCREEN: ui_message_beacon
void ui_message_beacon_screen_init(void);
lv_obj_t * ui_message_beacon;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label29;
// CUSTOM VARIABLES

// SCREEN: ui_enter_message
void ui_enter_message_screen_init(void);
lv_obj_t * ui_enter_message;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label56;
// CUSTOM VARIABLES

// SCREEN: ui_main_waypoints
void ui_main_waypoints_screen_init(void);
lv_obj_t * ui_main_waypoints;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_sub_waypoint1
void ui_sub_waypoint1_screen_init(void);
lv_obj_t * ui_sub_waypoint1;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Label54;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
// CUSTOM VARIABLES

// SCREEN: ui_sub_waypoint2
void ui_sub_waypoint2_screen_init(void);
lv_obj_t * ui_sub_waypoint2;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Label43;
// CUSTOM VARIABLES

// SCREEN: ui_sub_waypoint3
void ui_sub_waypoint3_screen_init(void);
lv_obj_t * ui_sub_waypoint3;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Panel19;
lv_obj_t * ui_Label55;
// CUSTOM VARIABLES

// SCREEN: ui_track_waypoint
void ui_track_waypoint_screen_init(void);
lv_obj_t * ui_track_waypoint;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Label46;
// CUSTOM VARIABLES

// SCREEN: ui_del_waypoint
void ui_del_waypoint_screen_init(void);
lv_obj_t * ui_del_waypoint;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Label47;
lv_obj_t * ui_Label48;
lv_obj_t * ui_Label49;
// CUSTOM VARIABLES

// SCREEN: ui_add_waypoint
void ui_add_waypoint_screen_init(void);
lv_obj_t * ui_add_waypoint;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label17;
// CUSTOM VARIABLES

// SCREEN: ui_main_messages
void ui_main_messages_screen_init(void);
lv_obj_t * ui_main_messages;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

// SCREEN: ui_sub_message1
void ui_sub_message1_screen_init(void);
lv_obj_t * ui_sub_message1;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
// CUSTOM VARIABLES

// SCREEN: ui_sub_message3
void ui_sub_message3_screen_init(void);
lv_obj_t * ui_sub_message3;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Label33;
// CUSTOM VARIABLES

// SCREEN: ui_sub_message2
void ui_sub_message2_screen_init(void);
lv_obj_t * ui_sub_message2;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Label50;
lv_obj_t * ui_Label51;
lv_obj_t * ui_Label52;
lv_obj_t * ui_Label53;
// CUSTOM VARIABLES

// SCREEN: ui_sub_message4
void ui_sub_message4_screen_init(void);
lv_obj_t * ui_sub_message4;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label65;
lv_obj_t * ui_Label66;
// CUSTOM VARIABLES

// SCREEN: ui_view_message
void ui_view_message_screen_init(void);
lv_obj_t * ui_view_message;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Label34;
// CUSTOM VARIABLES

// SCREEN: ui_enter_message_blank
void ui_enter_message_blank_screen_init(void);
lv_obj_t * ui_enter_message_blank;
lv_obj_t * ui_Label67;
lv_obj_t * ui_Label68;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_beacons_screen_init();
    ui_sub_beacon1_screen_init();
    ui_sub_beacon2_screen_init();
    ui_sub_beacon3_screen_init();
    ui_sub_beacon4_screen_init();
    ui_track_beacon_screen_init();
    ui_tracking_n_screen_init();
    ui_tracking_e_screen_init();
    ui_tracking_s_screen_init();
    ui_tracking_w_screen_init();
    ui_message_beacon_screen_init();
    ui_enter_message_screen_init();
    ui_main_waypoints_screen_init();
    ui_sub_waypoint1_screen_init();
    ui_sub_waypoint2_screen_init();
    ui_sub_waypoint3_screen_init();
    ui_track_waypoint_screen_init();
    ui_del_waypoint_screen_init();
    ui_add_waypoint_screen_init();
    ui_main_messages_screen_init();
    ui_sub_message1_screen_init();
    ui_sub_message3_screen_init();
    ui_sub_message2_screen_init();
    ui_sub_message4_screen_init();
    ui_view_message_screen_init();
    ui_enter_message_blank_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
//    lv_disp_load_scr(ui_main_beacons);
}
