// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Buddy_Beacon

#ifndef _BUDDY_BEACON_UI_H
#define _BUDDY_BEACON_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_main_beacons
void ui_main_beacons_screen_init(void);
extern lv_obj_t * ui_main_beacons;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_sub_beacon1
void ui_sub_beacon1_screen_init(void);
extern lv_obj_t * ui_sub_beacon1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

// SCREEN: ui_sub_beacon2
void ui_sub_beacon2_screen_init(void);
extern lv_obj_t * ui_sub_beacon2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label37;
// CUSTOM VARIABLES

// SCREEN: ui_sub_beacon3
void ui_sub_beacon3_screen_init(void);
extern lv_obj_t * ui_sub_beacon3;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label40;
// CUSTOM VARIABLES

// SCREEN: ui_sub_beacon4
void ui_sub_beacon4_screen_init(void);
extern lv_obj_t * ui_sub_beacon4;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label83;
extern lv_obj_t * ui_Label84;
// CUSTOM VARIABLES

// SCREEN: ui_track_beacon
void ui_track_beacon_screen_init(void);
extern lv_obj_t * ui_track_beacon;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
// CUSTOM VARIABLES

// SCREEN: ui_tracking_n
void ui_tracking_n_screen_init(void);
extern lv_obj_t * ui_tracking_n;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Label58;
// CUSTOM VARIABLES

// SCREEN: ui_tracking_e
void ui_tracking_e_screen_init(void);
extern lv_obj_t * ui_tracking_e;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Label60;
// CUSTOM VARIABLES

// SCREEN: ui_tracking_s
void ui_tracking_s_screen_init(void);
extern lv_obj_t * ui_tracking_s;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_Label64;
// CUSTOM VARIABLES

// SCREEN: ui_tracking_w
void ui_tracking_w_screen_init(void);
extern lv_obj_t * ui_tracking_w;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Label62;
// CUSTOM VARIABLES

// SCREEN: ui_message_beacon
void ui_message_beacon_screen_init(void);
extern lv_obj_t * ui_message_beacon;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label29;
// CUSTOM VARIABLES

// SCREEN: ui_enter_message
void ui_enter_message_screen_init(void);
extern lv_obj_t * ui_enter_message;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label56;
// CUSTOM VARIABLES

// SCREEN: ui_main_waypoints
void ui_main_waypoints_screen_init(void);
extern lv_obj_t * ui_main_waypoints;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_sub_waypoint1
void ui_sub_waypoint1_screen_init(void);
extern lv_obj_t * ui_sub_waypoint1;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
// CUSTOM VARIABLES

// SCREEN: ui_sub_waypoint2
void ui_sub_waypoint2_screen_init(void);
extern lv_obj_t * ui_sub_waypoint2;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
// CUSTOM VARIABLES

// SCREEN: ui_sub_waypoint3
void ui_sub_waypoint3_screen_init(void);
extern lv_obj_t * ui_sub_waypoint3;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label55;
// CUSTOM VARIABLES

// SCREEN: ui_track_waypoint
void ui_track_waypoint_screen_init(void);
extern lv_obj_t * ui_track_waypoint;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label46;
// CUSTOM VARIABLES

// SCREEN: ui_del_waypoint
void ui_del_waypoint_screen_init(void);
extern lv_obj_t * ui_del_waypoint;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label49;
// CUSTOM VARIABLES

// SCREEN: ui_add_waypoint
void ui_add_waypoint_screen_init(void);
extern lv_obj_t * ui_add_waypoint;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label17;
// CUSTOM VARIABLES

// SCREEN: ui_main_messages
void ui_main_messages_screen_init(void);
extern lv_obj_t * ui_main_messages;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

// SCREEN: ui_sub_message1
void ui_sub_message1_screen_init(void);
extern lv_obj_t * ui_sub_message1;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
// CUSTOM VARIABLES

// SCREEN: ui_sub_message3
void ui_sub_message3_screen_init(void);
extern lv_obj_t * ui_sub_message3;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
// CUSTOM VARIABLES

// SCREEN: ui_sub_message2
void ui_sub_message2_screen_init(void);
extern lv_obj_t * ui_sub_message2;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label53;
// CUSTOM VARIABLES

// SCREEN: ui_sub_message4
void ui_sub_message4_screen_init(void);
extern lv_obj_t * ui_sub_message4;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_Label66;
// CUSTOM VARIABLES

// SCREEN: ui_view_message
void ui_view_message_screen_init(void);
extern lv_obj_t * ui_view_message;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label34;
// CUSTOM VARIABLES

// SCREEN: ui_enter_message_blank
void ui_enter_message_blank_screen_init(void);
extern lv_obj_t * ui_enter_message_blank;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Label68;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
